### ISSUE TITLE
Error rendering/previewing a replay with a chat whose player has been removed

### ISSUE THREAD

**Issue by ballparts** [chrahunt/TagProReplays#104]
If a player is removed from a replay file after cropping, but a chat that references that player remains, the in-browser previewer will error. Example replay file: http://dropcanvas.com/4szmv

**Comment by ballparts** [comment]
Possible duplicate issue to [this closed issue](https://github.com/chrahunt/TagProReplays/issues/89). @chrahunt same thing?

**Comment by chrahunt** [comment]
No, the problem here is that the chats may outlive their creator. We want to keep the chat for as long as it is supposed to show up but the question is what do we do about the player. Do we need to keep the object  in the replay or maybe move the name to the chat itself? In any case now we need to check for and remove any chats that reference a player that is no longer present.

**Comment by ballparts** [comment]
Probably the best option is to store the player name in the chat object when it is recorded.

**Comment by chrahunt** [comment]
And auth and team.
