### ISSUE TITLE
gameEndsAt is expected to have 2 items, but sometimes has 3

### ISSUE THREAD

**Issue by Headshot305** [chrahunt/TagProReplays#191]
Your replay (d.txt) had a problem:
Validation error: schema validation failure; data/gameEndsAt should match exactly one schema in oneOf

http://dropcanvas.com/#3K6w16678vD0x6

Also on an unrelated note there seems to be a bug with rendering where certain tiles take one too many row/columns of pixels from texturepacks creating some odd artifacting. 
https://www.reddit.com/r/TagPro/comments/6lj8s8/need_some_help_with_tagpro_replays/

**Comment by chrahunt** [comment]
Thanks, I was able to determine the cause of your issue. So I can have an example for testing can you please reupload the replay? It has expired on dropcanvas.

The validation that the extension does is only expecting at most two items in the `gameEndsAt` property, but in this case there are 3 present. This can happen if recording script initializes after the `tagpro` object but before the initial pre-game `time` event. When that happens any replays that are recorded after play starts will have three values in `gameEndsAt`: the initial value of `tagpro.gameEndsAt` (0), the initial `time` event setting the pre-game countdown, and the `time` event that corresponds to the start of play. The fix is to accept up to three values in the renderer and change the schema to allow replays that have this quirk.

**Comment by Headshot305** [comment]
http://dropcanvas.com/cgxz0

hopefully this works here
