### ISSUE TITLE
Show random replays behind the TagPro logo on the homepage

### ISSUE THREAD

**Issue by wilcooo** [chrahunt/TagProReplays#224]
This seems like a nice addition to me.

![](https://i.imgur.com/gxHbuD4.png)

**Comment by chrahunt** [comment]
That does look nice. Wherever possible I want to move the extension away from directly injecting content into the TagPro site. This helps avoid conflict with userscripts, keeps the extension robust against changes to the TagPro site, and reduces maintenance burden (since it is then easier to test). For that reason I don't think this should be in the extension and will close this issue. That said, if someone is willing to write a dedicated userscript for the functionality then I would be happy to work with them to expose an interface to the extension data to enable it.
