### ISSUE TITLE
Cap Record option

### ISSUE THREAD

**Issue by nrabins** [chrahunt/TagProReplays#24]
This would be neat, I think, and make replays a little more manageable.

The idea is that the recorder would always record starting from a few seconds before you grabbed the flag, and then stop the recording a second or two after you cap. If you don't cap, it would delete the recording (unless manually saved by the user).

I think this could work a couple of different ways, so hit me up in practice if you want to talk about it.

The goal would be full capture of caps taking longer than your set record amount, so you can get the whole capping experience.

**Comment by ballparts** [comment]
Cool idea. This is similar to [this issue](https://github.com/ballparts/TagProReplays/issues/21), as both would require a major reworking of the replay-recording code.

Right now, snaps and I (mostly snaps) are working on refactoring much of my code in preparation for a huge overall of the storage system along with some other changes. I also have less time in the next couple weeks than usual, means I probably won't get to this soon.

We should still talk about it at practice tonight, since I don't have a good idea how to implement it right now.

**Comment by chrahunt** [comment]
Closing this. New limitations are going to be put in place on replay size/duration to make the extension/backing database more stable so an open-ended recording is a no-go.
